program badboy ()
function nonsemicolonterminatedfunction(const bar : integer) : integer
begin end
function foo(const : integer) : integer
begin end
var foo : integer;
const bar := ;
const := 3;
var a : int;
a : int;
var a : integer
var a,b,c integer;
begin
  first fail;
  a:=b:=c;
  write(a;
  if (a) write(a);
  if (a) then a+b
  else b;
  if (a) write(a)
  else write("nope");
  a := 3
  a := 3;
  error socio;
end.
